apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: nodejs-memory
spec:
  maxReplicas: 12
  minReplicas: 10
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nodejs
  metrics:
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: 60
